config/routes.rb
Rails.application.routes.draw do
  root "appointments#index"

  resources :appointments, except: [:new]
  resources :patients, except: [:destroy]

  resources :physicians, except: [:destroy] do
    resources :time_slots, only: [:index] do
      get 'appointments/new', to: 'appointments#new'
    end

    get 'time_slots/:date', to: 'time_slots#daily_slots', as: 'daily_slots'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :physician

  validates :date,
            :patient,
            :physician, presence: true

  def date_time
    date.strftime('%d.%m.%Y, %H:%M')
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :physicians, through: :appointments

  validates :first_name,
            :last_name,
            :date_of_birth, presence: true

  def full_name
    full_name = "#{self.last_name} #{self.first_name}"
    full_name += " #{self.patronymic}" if self.patronymic

    full_name
  end

  def short_date_of_birth
    date_of_birth.strftime('%d.%m.%Y')
  end
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments
  has_many :time_slots

  validates :specialty,
            :work_time, presence: true

  serialize :work_time, Hash
end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
  belongs_to :physician
  belongs_to :appointment, optional: true

  validates :date, :time, :physician, presence: true

  def date_time
    "#{date.strftime('%d.%m.%Y')}, #{time}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, except: %i[index new create]

  def index
    @appointments = Appointment.all
  end

  def show
  end

  def new
    @appointment = Appointment.new(physician_id: params[:physician_id], date: params[:date])
  end

  def edit
  end

  def create
    @appointment = Appointment.new(appointment_params)

    if @appointment.save
      redirect_to @appointment, notice: 'Appointment was successfully created.'
    else
      flash.now[:error] = @appointment.errors.full_messages.join(', ')
      render :new
    end
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment, notice: 'Appointment was successfully updated.'
    else
      flash.now[:error] = @appointment.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path, notice: 'Appointment was successfully deleted.'
  end

  private

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:patient_id, :physician_id, :date)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, except: %i[index new create]

  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient, notice: 'Patient was successfully created.'
    else
      flash.now[:error] = @patient.errors.full_messages.join(', ')
      render :new
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: 'Patient was successfully updated.'
    else
      flash.now[:error] = @patient.errors.full_messages.join(', ')
      render :edit
    end
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :patronymic, :date_of_birth)
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, except: %i[index new create]

  def index
    @physicians = Physician.all
  end

  def show
  end

  def new
    @physician = Physician.new
  end

  def edit
  end

  def create
    @physician = Physician.new(physician_params)

    if @physician.save
      redirect_to @physician, notice: 'Physician was successfully created.'
    else
      flash.now[:error] = @physician.errors.full_messages.join(', ')
      render :new
    end
  end

  def update
    if @physician.update(patient_params)
      redirect_to @physician, notice: 'Physician was successfully updated.'
    else
      flash.now[:error] = @physician.errors.full_messages.join(', ')
      render :edit
    end
  end

  private

  def set_physician
    @physician = Physician.find(params[:id])
  end

  def physician_params
    params.require(:physician).permit(:specialty, :work_time)
  end
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  def index
    @time_slots = TimeSlot.where(physician_id: params[:physician_id])
    @time_slots_days = @time_slots.pluck(:date).uniq
  end

  def daily_slots
    @time_slots = TimeSlot.where(physician_id: params[:physician_id])
    @daily_slots = @time_slots.where(date: params[:date])
  end

  private

  def time_slot_params
    params.require(:time_slot).permit(:date, :time, :taken, :physician_id, :appointment_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/views/appointments/_appointment.html.erb
<tr id="appointment-<%= "#{appointment.id}" %>">
  <td><%= appointment.id %></td>
  <td><%= appointment.date_time %></td>

  <td>
    <%= link_to appointment.patient.full_name, patient_path(appointment.patient) %>
  </td>

  <td>
    <%= link_to appointment.physician.specialty, physicians_path(appointment.physician) %>
  </td>

  <td>
    <%= link_to fa_icon('eye'), appointment_path(appointment), class: "px-2 label label-primary" %>
    <%= link_to fa_icon('pencil'), edit_appointment_path(appointment), class: "px-2 label label-primary" %>
  </td>
</tr>

app/views/appointments/_form.html.erb
<%= simple_form_for @appointment, validate: true do |f| %>
  <%= f.hidden_field :physician_id %>
  <%= f.hidden_field :date, time_slot.date %>

  <h4>Choose a patient</h4>
  <div class="form-group">
    <%= f.label :patient %><br>
    <%= f.collection_select :patient_id, Patient.all, :id, :full_name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>

  <% if @appointment.persisted? %>
    <div class="mt-5">
      <%= link_to 'Delete appointment', @appointment,
                  method: :delete, data: {confirm: 'Are you sure?'}, class: 'text-danger' %>
    </div>
  <% end %>
<% end %>

app/views/appointments/_nav_index_new.html.erb
<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <%= link_to 'List', appointments_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Create new', physicians_path, class: 'nav-link' %>
  </li>
</ul>

app/views/appointments/_nav_show_edit.html.erb
<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <%= link_to 'Show', appointment_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Edit', edit_appointment_path, class: 'nav-link' %>
  </li>
</ul>

app/views/appointments/edit.html.erb
<%= render partial: 'nav_show_edit' %>

<div class="row">
  <div class="col">
    <%= render 'form' %>
  </div>
</div>

app/views/appointments/index.html.erb
<%= render partial: 'nav_index_new' %>

<div class="row justify-content-md-center">
  <div class="col table-responsive">
    <table class="table table-striped mt-3">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Date</th>
        <th scope="col">Patient</th>
        <th scope="col">Physician</th>
        <th scope="col"></th>
      </tr>
      </thead>
      <tbody>
      <%= render partial: 'appointment', collection: @appointments %>
      </tbody>
    </table>
  </div>
</div>



app/views/appointments/new.html.erb
<%= render partial: 'nav_index_new' %>

<%= render partial: 'form' %>



app/views/appointments/show.html.erb
<%= render partial: 'nav_show_edit' %>

<dl>
  <dt class="badge badge-primary">Date</dt>
  <dd><h4><%= @appointment.date_time %></h4></dd>

  <dt class="badge badge-primary">Patient</dt>
  <dd><h4><%= @appointment.patient.full_name %></h4></dd>

  <dt class="badge badge-primary">Physician</dt>
  <dd><h4><%= @appointment.physician.specialty %></h4></dd>
</dl>


app/views/layouts/_nav.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container">
    <%= link_to 'Clinic', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to 'Appointments', appointments_path, class: 'nav-item nav-link' %>
        <%= link_to 'Patients', patients_path, class: 'nav-item nav-link' %>
        <%= link_to 'Physicians', physicians_path, class: 'nav-item nav-link' %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clinic</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/nav' %>

    <div class="container">
      <div class="row">
        <div class="col">
          <%= flash_messages %>

          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= simple_form_for @patient, validate: true do |f| %>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :patronymic %><br>
    <%= f.text_field :patronymic, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :date_of_birth %><br>
    <%= f.date_field :date_of_birth, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/patients/_nav_index_new.html.erb
<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <%= link_to 'List', patients_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Create new', new_patient_path, class: 'nav-link' %>
  </li>
</ul>

app/views/patients/_nav_show_edit.html.erb
<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <%= link_to 'Show', patient_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Edit', edit_patient_path, class: 'nav-link' %>
  </li>
</ul>

app/views/patients/_patient.html.erb
<tr id="patient-<%= "#{patient.id}" %>">
  <td><%= patient.id %></td>
  <td><%= patient.full_name %></td>
  <td><%= patient.short_date_of_birth %></td>

  <td>
    <%= link_to fa_icon('eye'), patient_path(patient), class: "px-2 label label-primary" %>
    <%= link_to fa_icon('pencil'), edit_patient_path(patient), class: "px-2 label label-primary" %>
  </td>
</tr>

app/views/patients/edit.html.erb
<%= render partial: 'nav_show_edit' %>

<div class="row">
  <div class="col-md-4">
    <%= render 'form' %>
  </div>
</div>

app/views/patients/index.html.erb
<%= render partial: 'nav_index_new' %>

<div class="row">
  <div class="col table-responsive">
    <table class="table table-striped mt-3">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Full name</th>
        <th scope="col">Date of birth</th>
        <th scope="col"></th>
      </tr>
      </thead>
      <tbody>
      <%= render partial: 'patient', collection: @patients %>
      </tbody>
    </table>
  </div>
</div>

app/views/patients/new.html.erb
<%= render partial: 'nav_index_new' %>

<div class="row">
  <div class="col-md-4">
    <%= render 'form' %>
  </div>
</div>

app/views/patients/show.html.erb
<%= render partial: 'nav_show_edit' %>

<dl>
  <dt class="badge badge-primary">Full name</dt>
  <dd><h4><%= @patient.full_name %></h4></dd>

  <dt class="badge badge-primary">Date of birth</dt>
  <dd><h4><%= @patient.short_date_of_birth %></h4></dd>
</dl>

app/views/physicians/_form.html.erb
<%= simple_form_for @physician, validate: true do |f| %>
  <div class="form-group">
    <%= f.label :specialty %><br>
    <%= f.text_field :specialty, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/physicians/_nav_index_new.html.erb
<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <%= link_to 'List', physicians_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Create new', new_physician_path, class: 'nav-link' %>
  </li>
</ul>

app/views/physicians/_nav_show_edit.html.erb
<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <%= link_to 'Show', physician_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Edit', edit_physician_path, class: 'nav-link' %>
  </li>
</ul>

app/views/physicians/_physician.html.erb
<tr id="physician-<%= "#{physician.id}" %>">
  <td><%= physician.id %></td>
  <td><%= link_to physician.specialty, physician_time_slots_path(physician) %></td>

  <td>
    <% physician.work_time.each do |day, time| %>
      <div><%= day %>: <%= time.join(', ') %></div>
    <% end %>
  </td>

  <td>
    <%= link_to fa_icon('eye'), physician_path(physician), class: "px-2 label label-primary" %>
    <%= link_to fa_icon('pencil'), edit_physician_path(physician), class: "px-2 label label-primary" %>
  </td>
</tr>

app/views/physicians/edit.html.erb
<%= render partial: 'nav_show_edit' %>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/physicians/index.html.erb
<%= render partial: 'nav_index_new' %>

<h4>Choose a physician to create an appointment</h4>

<div class="row">
  <div class="col table-responsive">
    <table class="table table-striped mt-3">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Specialty</th>
        <th scope="col">Work time</th>
        <th scope="col"></th>
      </tr>
      </thead>
      <tbody>
      <%= render partial: 'physician', collection: @physicians %>
      </tbody>
    </table>
  </div>
</div>

app/views/physicians/new.html.erb
<%= render partial: 'nav_index_new' %>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/physicians/show.html.erb
<%= render partial: 'nav_show_edit' %>

<dl>
  <dt class="badge badge-primary">Specialty</dt>
  <dd><h4><%= @physician.specialty %></h4></dd>

  <dt class="badge badge-primary">Work time</dt>
  <dd>
    <p>
      <% @physician.work_time.each do |day, time| %>
        <div><%= day %>: <%= time.join(', ') %></div>
      <% end %>
    </p>
  </dd>
</dl>

app/views/time_slots/daily_slots.erb
<h4>Choose appointment time</h4>

<div class="row">
  <div class="col-md-3">
    <div class="list-group list-group-flush">
      <% @daily_slots.each do |slot| %>
        <div class="list-group-item">
          <%= link_to slot.time, physician_time_slot_appointments_new_path %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/time_slots/index.html.erb
<h4>Choose appointment day</h4>

<div class="row">
  <div class="col-md-3">
    <div class="list-group list-group-flush">
      <% @time_slots_days.each do |day| %>
        <div class="list-group-item">
          <%= link_to day.strftime('%d.%m.%Y'), physician_daily_slots_path(date: day) %>
        </div>
      <% end %>
    </div>
  </div>
</div>